#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Dedupe-by-URL and clone
#   - Canonicalizes URL (lowercase + strip trailing .git).
#   - Skips subsequent duplicates and shows who claimed it first.
# ──────────────────────────────────────────────────────────────────────────────

for cmd in tr sed; do
	if ! command -v "$cmd" &>/dev/null; then
		echo "$cmd could not be found. Please install $cmd."
		exit 1
	fi
done

function normalize_url() {
	# to-lowercase, strip trailing ".git"
	# also collapse any accidental double slashes after host
	local u="$1"
	u="$(printf '%s' "$u" | tr '[:upper:]' '[:lower:]')"
	u="$(printf '%s' "$u" | sed -E 's#\.git$##')"
	u="$(printf '%s' "$u" | sed -E 's#(https?://[^/]+)//+#\1/#')"
	printf '%s' "$u"
}

repos=(
	"Arch-Hyprland https://github.com/JaKooLit/Arch-Hyprland.git"
	"CMake https://github.com/Kitware/CMake.git"
	"ChemFST https://github.com/esrehmki/ChemFST.git"
	"Hyprland https://github.com/hyprwm/Hyprland.git"
	"LSP https://github.com/sublimelsp/LSP.git"
	"MathJax https://github.com/mathjax/MathJax.git"
	"MathJax-demos-node https://github.com/mathjax/MathJax-demos-node.git"
	"MathJax-docs https://github.com/mathjax/MathJax-docs.git"
	"MoBi https://github.com/Open-Systems-Pharmacology/MoBi.git"
	"NvChad https://github.com/NvChad/NvChad"
	"OSPSuite-R https://github.com/Open-Systems-Pharmacology/OSPSuite-R.git"
	"OSPSuite.Core https://github.com/Open-Systems-Pharmacology/OSPSuite.Core.git"
	"PK-Py https://github.com/peytoncchen/PK-Py.git"
	"PK-Sim https://github.com/Open-Systems-Pharmacology/PK-Sim.git"
	"Packages https://github.com/sublimehq/Packages.git"
	"PerlNavigator https://github.com/bscan/PerlNavigator.git"
	"RHash https://github.com/rhash/RHash.git"
	"ScaffoldGraph https://github.com/UCLCheminformatics/ScaffoldGraph.git"
	"SeleniumBase https://github.com/seleniumbase/SeleniumBase.git"
	"ShaderLang https://github.com/NazaraEngine/ShaderLang.git"
	"SublimeAllAutocomplete https://github.com/alienhard/SublimeAllAutocomplete.git"
	"UserScripts https://github.com/Epineph/UserScripts"
	"WoeUSB-ng https://github.com/WoeUSB/WoeUSB-ng.git"
	"alacritty https://github.com/alacritty/alacritty.git"
	"alacritty-theme https://github.com/alacritty/alacritty-theme.git"
	"asm-lsp https://github.com/bergercookie/asm-lsp.git"
	"autotools-language-server https://github.com/Freed-Wu/autotools-language-server.git"
	"awk-language-server https://github.com/Beaglefoot/awk-language-server.git"
	"backup_scripts https://github.com/Epineph/backup_scripts.git"
	"base16-builder-go https://github.com/tinted-theming/base16-builder-go.git"
	"base16-shell https://github.com/chriskempson/base16-shell.git"
	"bash-language-server https://github.com/bash-lsp/bash-language-server.git"
	"bash-options https://github.com/stenalpjolly/bash-options.git"
	"bat https://github.com/sharkdp/bat.git"
	"bat-extras https://github.com/eth-p/bat-extras.git"
	"bats-assert https://github.com/bats-core/bats-assert.git"
	"bats-core https://github.com/bats-core/bats-core.git"
	"bats-file https://github.com/bats-core/bats-file.git"
	"bats-mock https://github.com/buildkite-plugins/bats-mock.git"
	"bats-support https://github.com/bats-core/bats-support.git"
	"beautysh https://github.com/lovesegfault/beautysh.git"
	"better-shell-syntax https://github.com/jeff-hykin/better-shell-syntax.git"
	"binaryen https://github.com/WebAssembly/binaryen.git"
	"broot https://github.com/Canop/broot.git"
	"carapace-bin https://github.com/carapace-sh/carapace-bin.git"
	"cargo-commander https://github.com/simonhyll/cargo-commander.git"
	"cargo-fuzz https://github.com/rust-fuzz/cargo-fuzz.git"
	"chainer-chemistry https://github.com/chainer/chainer-chemistry.git"
	"chembl_webresource_client https://github.com/chembl/chembl_webresource_client.git"
	"clap https://github.com/clap-rs/clap.git"
	"couchbase-shell https://github.com/couchbaselabs/couchbase-shell.git"
	"course-pharmacokinetic-modelling https://github.com/matthiaskoenig/course-pharmacokinetic-modelling.git"
	"crowbook https://github.com/lise-henry/crowbook.git"
	"delta https://github.com/dandavison/delta.git"
	"difftastic https://github.com/Wilfred/difftastic.git"
	"direnv https://github.com/direnv/direnv.git"
	"dotbot https://github.com/anishathalye/dotbot.git"
	"dotfiles https://github.com/casey/dotfiles.git"
	"doxide https://github.com/lawmurray/doxide.git"
	"doxygen https://github.com/doxygen/doxygen"
	"dracula.nvim https://github.com/Mofiqul/dracula.nvim.git"
	"etc_jupyterlab_nbgrader_validate https://github.com/educational-technology-collective/etc_jupyterlab_nbgrader_validate.git"
	"eza https://github.com/eza-community/eza.git"
	"eza-themes https://github.com/eza-community/eza-themes.git"
	"fancybook https://github.com/drahnr/fancybook.git"
	"fd https://github.com/sharkdp/fd.git"
	"fidget.nvim https://github.com/j-hui/fidget.nvim.git"
	"flavours https://github.com/Misterio77/flavours.git"
	"fzf https://github.com/junegunn/fzf.git"
	"generate_install_command https://github.com/Epineph/generate_install_command"
	"gocc https://github.com/goccmack/gocc.git"
	"html-to-markdown https://github.com/JohannesKaufmann/html-to-markdown.git"
	"htmx-lsp https://github.com/ThePrimeagen/htmx-lsp.git"
	"hydra-lsp https://github.com/Retsediv/hydra-lsp.git"
	"ipyflex https://github.com/trungleduc/ipyflex.git"
	"ipykernel https://github.com/ipython/ipykernel"
	"ipynb-to-md https://github.com/diaakasem/ipynb-to-md.git"
	"ipython https://github.com/ipython/ipython"
	"ipywidgets https://github.com/jupyter-widgets/ipywidgets.git"
	"jrep https://github.com/joshua-laughner/jrep.git"
	"jsoncpp https://github.com/open-source-parsers/jsoncpp.git"
	"jupyter https://github.com/jupyter/jupyter"
	"jupyter_client https://github.com/jupyter/jupyter_client"
	"jupyter_core https://github.com/jupyter/jupyter_core"
	"jupyterlab https://github.com/jupyterlab/jupyterlab"
	"jupyterlab-lsp https://github.com/jupyter-lsp/jupyterlab-lsp.git"
	"jupyterlab_sublime https://github.com/zhangfeiran/jupyterlab_sublime.git"
	"just https://github.com/casey/just.git"
	"kakoune https://github.com/mawww/kakoune.git"
	"langserver https://github.com/nim-lang/langserver.git"
	"lapce https://github.com/lapce/lapce.git"
	"lazygit https://github.com/jesseduffield/lazygit.git"
	"libressl-3.9.2 https://github.com/libressl-portable/portable.git"
	"linkify-it https://github.com/markdown-it/linkify-it.git"
	"llvmlite https://github.com/numba/llvmlite.git"
	"lsd https://github.com/lsd-rs/lsd.git"
	"luau-lsp https://github.com/JohnnyMorganz/luau-lsp.git"
	"magic-wormhole https://github.com/magic-wormhole/magic-wormhole.git"
	"manage_lvm_space https://github.com/Epineph/manage_lvm_space.git"
	"markdown https://github.com/Python-Markdown/markdown.git"
	"markdown-it https://github.com/markdown-it/markdown-it.git"
	"mason-registry https://github.com//mason-org/mason-registry.git"
	"mason.nvim https://github.com/mason-org/mason.nvim.git"
	"mdBook https://github.com/rust-lang/mdBook.git"
	"mdbook-bash-tutorial https://github.com/filariow/mdbook-bash-tutorial.git"
	"mdbook-epub https://github.com/Michael-F-Bryan/mdbook-epub.git"
	"mdbook-inline-highlighting https://github.com/phoenixr-codes/mdbook-inline-highlighting.git"
	"mdbook-katex https://github.com/lzanini/mdbook-katex.git"
	"mdbook-latex https://github.com/lbeckman314/mdbook-latex.git"
	"mdbook-preprocessor-utils https://github.com/willcrichton/mdbook-preprocessor-utils.git"
	"mdbook-scientific https://github.com/drahnr/mdbook-scientific.git"
	"mdcat https://github.com/swsnr/mdcat.git"
	"mdformat https://github.com/hukkin/mdformat.git"
	"mdformat-ruff https://github.com/Freed-Wu/mdformat-ruff.git"
	"mdformat-shfmt https://github.com/hukkin/mdformat-shfmt.git"
	"mdformat-web https://github.com/hukkin/mdformat-web.git"
	"meson-python https://github.com/mesonbuild/meson-python.git"
	"micromamba-releases https://github.com/mamba-org/micromamba-releases.git"
	"miller https://github.com/johnkerl/miller.git"
	"mkdocs https://github.com/mkdocs/mkdocs.git"
	"move https://github.com/move-language/move.git"
	"mulle-bashfunctions https://github.com/mulle-nat/mulle-bashfunctions.git"
	"mutt-language-server https://github.com/neomutt/mutt-language-server.git"
	"my_R_config https://github.com/Epineph/my_R_config.git"
	"my_scripts https://github.com/Epineph/my_scripts.git"
	"nbread https://github.com/tnwei/nbread.git"
	"nelua-lsp https://github.com/codehz/nelua-lsp.git"
	"nelua.vim https://github.com/stefanos82/nelua.vim.git"
	"neoformat https://github.com/sbdchd/neoformat.git"
	"networkx https://github.com/networkx/networkx.git"
	"next-ls https://github.com/elixir-tools/next-ls.git"
	"nickel https://github.com/tweag/nickel.git"
	"nil https://github.com/oxalica/nil.git"
	"nimlsp https://github.com/PMunch/nimlsp.git"
	"ninja https://github.com/ninja-build/ninja.git"
	"nomad-lsp https://github.com//juliosueiras/nomad-lsp.git"
	"nteract https://github.com/nteract/nteract.git"
	"numba https://github.com/numba/numba"
	"numd https://github.com/nushell-prophet/numd.git"
	"numpy https://github.com/numpy/numpy.git"
	"nushell https://github.com/nushell/nushell.git"
	"nvim-dap https://github.com/mfussenegger/nvim-dap.git"
	"nvim-idris2 https://github.com/ShinKage/nvim-idris2.git"
	"nvim-jdtls https://github.com/mfussenegger/nvim-jdtls.git"
	"nvim_conf https://github.com/Epineph/nvim_conf"
	"ocaml https://github.com/ocaml/ocaml"
	"onedrive https://github.com/abraunegg/onedrive.git"
	"oniguruma https://github.com/defuz/oniguruma.git"
	"openbabel https://github.com/openbabel/openbabel.git"
	"openscad-LSP https://github.com/Leathong/openscad-LSP.git"
	"openscad-language-server https://github.com/dzhu/openscad-language-server.git"
	"oxc https://github.com/oxc-project/oxc.git"
	"package_control https://github.com/wbond/package_control.git"
	"pandoc https://github.com/jgm/pandoc.git"
	"papaja https://github.com/crsh/papaja.git"
	"paru https://aur.archlinux.org/paru.git"
	"pascal-language-server https://github.com/genericptr/pascal-language-server.git"
	"persist https://github.com/visdesignlab/persist.git"
	"pest-ide-tools https://github.com/pest-parser/pest-ide-tools.git"
	"phan https://github.com/phan/phan.git"
	"pharmsol https://github.com/LAPKB/pharmsol.git"
	"phpactor https://github.com/phpactor/phpactor.git"
	"pinage404-vscode-extension-packs https://gitlab.com/pinage404/pinage404-vscode-extension-packs"
	"piping-server https://github.com/nwtgck/piping-server.git"
	"piping-server-rust https://github.com/nwtgck/piping-server-rust.git"
	"plotpy https://github.com/cpmech/plotpy.git"
	"portable https://github.com/libressl-portable/portable.git"
	"prettier https://github.com/prettier/prettier.git"
	"processing-sublime https://github.com/b-g/processing-sublime.git"
	"python-lsp-black https://github.com/python-lsp/python-lsp-black.git"
	"qtconsole https://github.com/jupyter/qtconsole"
	"quarto-cli https://github.com/quarto-dev/quarto-cli.git"
	"rdkit https://github.com/rdkit/rdkit.git"
	"rdkit-pypi https://github.com/kuelumbus/rdkit-pypi.git"
	"re2c https://github.com/skvadrik/re2c.git"
	"redshift https://github.com/jonls/redshift.git"
	"rhash https://github.com/rhash/RHash.git"
	"rich https://github.com/Textualize/rich.git"
	"rich-cli https://github.com/Textualize/rich-cli.git"
	"ripgrep https://github.com/BurntSushi/ripgrep.git"
	"rmarkdown https://github.com/rstudio/rmarkdown.git"
	"rocks.nvim https://github.com/nvim-neorocks/rocks.nvim.git"
	"rust-csv https://github.com/BurntSushi/rust-csv.git"
	"ryacas https://github.com/r-cas/ryacas.git"
	"schemes https://github.com/tinted-theming/schemes.git"
	"semver https://github.com/semver/semver.git"
	"sh-syntax https://github.com/un-ts/sh-syntax.git"
	"sh-to-markdown https://github.com/rreinold/sh-to-markdown.git"
	"shiny-examples https://github.com/rstudio/shiny-examples.git"
	"slather https://github.com/SlatherOrg/slather.git"
	"sphinx https://github.com/sphinx-doc/sphinx.git"
	"starship https://github.com/starship/starship"
	"sublime https://github.com/JaredCubilla/sublime.git"
	"sublime-bats https://github.com/sptndc/sublime-bats.git"
	"swig https://github.com/swig/swig.git"
	"syntax-highlighter https://github.com/EvgeniyPeshkov/syntax-highlighter.git"
	"syntect https://github.com/trishume/syntect.git"
	"team https://github.com/rustwasm/team.git"
	"terminado https://github.com/jupyter/terminado"
	"thesisdown https://github.com/ismayc/thesisdown.git"
	"thorium-browser-bin https://aur.archlinux.org/thorium-browser-bin.git"
	"tinted-shell https://github.com/tinted-theming/tinted-shell.git"
	"tinty https://github.com/tinted-theming/tinty.git"
	"tinytex https://github.com/yihui/tinytex.git"
	"tree-sitter-phpdoc https://github.com/claytonrcarter/tree-sitter-phpdoc.git"
	"useful-scripts https://github.com/hoelzro/useful-scripts.git"
	"vcpkg https://github.com/microsoft/vcpkg.git"
	"vdplus https://github.com/visidata/vdplus.git"
	"vim-lsp https://github.com/prabirshrestha/vim-lsp.git"
	"visidata https://github.com/saulpw/visidata.git"
	"vs-shell-format https://github.com/foxundermoon/vs-shell-format.git"
	"wappalyzer-cli https://github.com/gokulapap/wappalyzer-cli.git"
	"windmill https://github.com/windmill-labs/windmill.git"
	"xcbuild https://github.com/facebook/xcbuild.git"
	"xsv https://github.com/BurntSushi/xsv.git"
	"yay https://aur.archlinux.org/yay.git"
	"zfsArch https://github.com/Epineph/zfsArch.git"
	"zoxide https://github.com/ajeetdsouza/zoxide.git"
	"404StarLink https://github.com/knownsec/404StarLink.git"
	"Havoc https://github.com/HavocFramework/Havoc.git"
	"Heimdallr https://github.com/Ghr07h/Heimdallr.git"
	"Increase-Instagram-follower https://github.com/giruu/Increase-Instagram-follower.git"
	"TrueSightKiller https://github.com/MaorSabag/TrueSightKiller.git"
	"WechatBakTool https://github.com/SuxueCode/WechatBakTool.git"
	"appium-boilerplate https://github.com/webdriverio/appium-boilerplate.git"
	"art-template https://github.com/goofychris/art-template.git"
	"awesome-webdriverio https://github.com/webdriverio/awesome-webdriverio.git"
	"axe-core-npm https://github.com/dequelabs/axe-core-npm.git"
	"bats-mock https://github.com/buildkite-plugins/bats-mock.git"
	"bottom https://github.com/ClementTsang/bottom.git"
	"btcloud https://github.com/flucont/btcloud.git"
	"cucumber-boilerplate https://github.com/webdriverio/cucumber-boilerplate.git"
	"generate_install_command https://github.com/Epineph/generate_install_command"
	"ipywidgets https://github.com/jupyter-widgets/ipywidgets.git"
	"jasmine-boilerplate https://github.com/webdriverio/jasmine-boilerplate.git"
	"jupytext https://github.com/mwouts/jupytext.git"
	"micromamba-releases https://github.com/mamba-org/micromamba-releases.git"
	"native-demo-app https://github.com/webdriverio/native-demo-app.git"
	"onionshare https://github.com/onionshare/onionshare.git"
	"playwright https://github.com/microsoft/playwright.git"
	"playwright-python https://github.com/microsoft/playwright-python.git"
	"query-selector-shadow-dom https://github.com/webdriverio/query-selector-shadow-dom.git"
	"rubygems https://github.com/rubygems/rubygems.git"
	"sandblocks https://github.com/hpi-swa/sandblocks.git"
	"selenium-standalone https://github.com/webdriverio/selenium-standalone.git"
	"td https://github.com/tdlib/td.git"
	"translators_CN https://github.com/l0o0/translators_CN.git"
	"uv https://github.com/astral-sh/uv.git"
	"vcpkg https://github.com/microsoft/vcpkg.git"
	"visual-testing https://github.com/webdriverio/visual-testing.git"
	"webdriverio https://github.com/webdriverio/webdriverio.git"
	"zoxide https://github.com/ajeetdsouza/zoxide.git"
	"APAstats https://github.com/achetverikov/APAstats.git"
	"rempsyc https://github.com/RemPsyc/rempsyc.git"
	"broom https://github.com/tidymodels/broom.git"
	"tidymodels https://github.com/tidymodels/tidymodels.git"
	"infer https://github.com/tidymodels/infer.git"
	"parsnip https://github.com/tidymodels/parsnip.git"
	"tmwr https://github.com/tidymodels/TMwR.git"
	"recipes https://github.com/tidymodels/recipes.git"
	"corrr https://github.com/tidymodels/corrr.git"
	"yardstick https://github.com/tidymodels/yardstick.git"
	"sample https://github.com/tidymodels/rsample.git"
	"tune https://github.com/tidymodels/tune.git"
	"stacks https://github.com/tidymodels/stacks.git"
	"tidypredict https://github.com/tidymodels/tidypredict.git"
	"textrecipes https://github.com/tidymodels/textrecipes.git"
	"embed https://github.com/tidymodels/embed.git"
	"themis https://github.com/tidymodels/themis.git"
	"butcher https://github.com/tidymodels/butcher.git"
	"censored https://github.com/tidymodels/censored.git"
	"probably https://github.com/tidymodels/probably.git"
	"tidyclust https://github.com/tidymodels/tidyclust.git"
	"hardhat https://github.com/tidymodels/hardhat.git"
	"tidyposterior https://github.com/tidymodels/tidyposterior.git"
	"reprex https://github.com/tidyverse/reprex.git"
	"pacman.store https://github.com/RubenKelevra/pacman.store.git"
	"archzfs https://github.com/archzfs/archzfs.git"
	"aur https://github.com/vbouchaud/aur.git"
	"packages https://github.com/BioArchLinux/Packages.git"
	"nvidia-304 https://github.com/flydiscohuebr/nvidia-304.git"
	"nvidia-340xx https://github.com/MichelBoucey/nvidia-340xx.git"
	"PKGBUILDS https://github.com/Martchus/PKGBUILDs.git"
  "functions-resources https://github.com/do-community/function-resources.git"
  "falco https://github.com/falcosecurity/falco.git"
)

function normalize_url() {
	# to-lowercase, strip trailing ".git"
	# also collapse any accidental double slashes after host
	local u="$1"
	u="$(printf '%s' "$u" | tr '[:upper:]' '[:lower:]')"
	u="$(printf '%s' "$u" | sed -E 's#\.git$##')"
	u="$(printf '%s' "$u" | sed -E 's#(https?://[^/]+)//+#\1/#')"
	printf '%s' "$u"
}

declare -A seen_by_url=() # canonical_url -> first_name
repo_dir="/home/heini/repos"
mkdir -p "$repo_dir"

echo "PATH is: $PATH"
echo "Cloning into: $repo_dir"
echo "—"

for repo in "${repos[@]}"; do
	name="$(echo "$repo" | cut -d ' ' -f 1)"
	url="$(echo "$repo" | cut -d ' ' -f 2)"
	canon="$(normalize_url "$url")"

	# If we have seen this URL already, skip with message
	if [[ -n "${seen_by_url[$canon]:-}" ]]; then
		echo "SKIP duplicate URL: $url  (first seen as: ${seen_by_url[$canon]})"
		continue
	fi
	seen_by_url[$canon]="$name"

	path="$repo_dir/$name"
	if [[ -d "$path/.git" ]]; then
		echo "$name already exists at $path."
		continue
	fi

	echo "Cloning $name from $url ..."
	git clone --recurse-submodules "$url" "$path"
done
