#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# python-pacman-nuke-plan
#
# Purpose:
#   Generate a bash script that removes *pacman-installed* Python-related
#   packages (typically those named python, python-*, python2, python2-*).
#
# Rationale:
#   When Python sonames bump (e.g., 3.x -> 3.y), you can end up with a “split”
#   userland where old packages remain installed but are incompatible.
#   This script produces a removable “reset plan” you can run now, and later
#   invert into an install plan if you keep the output.
#
# Safety defaults:
#   - By default, it EXCLUDES the core interpreter package "python" itself.
#   - It outputs a script; it does NOT execute removals unless you run the
#     generated script (or use --execute in this wrapper).
#
# Usage:
#   python-pacman-nuke-plan --output /root/remove-python-pkgs.sh
#   bash /root/remove-python-pkgs.sh
#
# Options:
#   -o, --output FILE       Write generated removal script to FILE
#                           (default: ./remove-python-pkgs.sh)
#   -x, --execute           Execute the generated script immediately
#   -i, --include-python    Include the core "python" package in removal set
#   -y, --yes               Add --noconfirm to pacman commands in output
#   -n, --dry-run           Print package list and planned command; do not write
#   -h, --help              Show help
#
# Exit codes:
#   0 on success, nonzero on error
# -----------------------------------------------------------------------------
set -euo pipefail

function _help() {
  cat <<'EOF'
python-pacman-nuke-plan

Generate (and optionally execute) a bash script that removes pacman-installed
Python-related packages.

Examples:
  python-pacman-nuke-plan
  python-pacman-nuke-plan -o /root/remove-python-pkgs.sh -y
  python-pacman-nuke-plan -i -o ./remove-all-python.sh
  python-pacman-nuke-plan -x -o /root/remove-python-pkgs.sh

Notes:
  - Default excludes the core "python" package for safety.
  - Removal uses: sudo pacman -Rns <pkgs...>
  - You can later invert the package list into an install plan:
      sudo pacman -S --needed <pkgs...>

Environment:
  HELP_PAGER  Override pager for --help (default: less -R if present else cat)
EOF
}

function _page_help() {
  local pager="${HELP_PAGER:-}"
  if [[ -z "$pager" ]]; then
    if command -v less >/dev/null 2>&1; then
      pager='less -R'
    else
      pager='cat'
    fi
  fi
  _help | eval "$pager"
}

function _die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

function _need_cmd() {
  command -v "$1" >/dev/null 2>&1 || _die "Missing required command: $1"
}

function _join_lines_to_words() {
  # stdin: newline-separated tokens
  # stdout: space-separated tokens
  awk 'NF { printf "%s%s", $0, (NR==NR ? OFS : OFS) } END { print "" }' OFS=' '
}

function _collect_python_pkgs() {
  local include_python="$1"

  # Collect installed packages that are plausibly Python-related by name.
  # We use pacman -Qq to avoid parsing "pacman -Qs" human output.
  #
  # Match:
  #   python
  #   python-foo
  #   python2
  #   python2-foo
  #
  # Exclude (by default):
  #   python  (core interpreter)
  #
  pacman -Qq \
    | awk '
        /^python($|-)/ || /^python2($|-)/
      ' \
    | awk -v inc="$include_python" '
        {
          if (inc == "1") {
            print
            next
          }
          if ($0 == "python") next
          print
        }
      ' \
    | sort -u
}

function _write_script() {
  local out="$1"
  local noconfirm="$2"
  local include_python="$3"

  local pkgs
  pkgs="$(_collect_python_pkgs "$include_python")"

  if [[ -z "$pkgs" ]]; then
    _die "No matching installed python packages found (nothing to do)."
  fi

  local pkgs_one_line
  pkgs_one_line="$(printf '%s\n' "$pkgs" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g; s/[[:space:]]$//')"

  {
    cat <<'EOF'
#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# remove-python-pkgs.sh (generated)
#
# Purpose:
#   Remove pacman-installed Python-related packages from this system.
#
# Notes:
#   - This was generated by python-pacman-nuke-plan.
#   - Edit the package list if you want to keep specific components.
# -----------------------------------------------------------------------------
set -euo pipefail

function _die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

function _need_cmd() {
  command -v "$1" >/dev/null 2>&1 || _die "Missing required command: $1"
}

_need_cmd pacman

if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
  sudo=''
else
  _need_cmd sudo
  sudo='sudo'
fi

EOF

    printf 'pkgs=(\n'
    printf '  %s\n' $pkgs_one_line
    printf ')\n\n'

    if [[ "$noconfirm" == "1" ]]; then
      cat <<'EOF'
"$sudo" pacman -Rns --noconfirm "${pkgs[@]}"
EOF
    else
      cat <<'EOF'
"$sudo" pacman -Rns "${pkgs[@]}"
EOF
    fi
  } >"$out"

  chmod 0755 "$out"
}

# ------------------------------ main -----------------------------------------
output='./remove-python-pkgs.sh'
do_execute='0'
include_python='0'
noconfirm='0'
dry_run='0'

while (($#)); do
  case "$1" in
    -o|--output)
      shift
      [[ $# -ge 1 ]] || _die "--output requires a file path"
      output="$1"
      ;;
    -x|--execute)
      do_execute='1'
      ;;
    -i|--include-python)
      include_python='1'
      ;;
    -y|--yes)
      noconfirm='1'
      ;;
    -n|--dry-run)
      dry_run='1'
      ;;
    -h|--help)
      _page_help
      exit 0
      ;;
    *)
      _die "Unknown argument: $1"
      ;;
  esac
  shift
done

_need_cmd pacman
_need_cmd awk
_need_cmd sort
_need_cmd sed
_need_cmd tr
_need_cmd chmod

pkgs="$(_collect_python_pkgs "$include_python")"
if [[ -z "$pkgs" ]]; then
  _die "No matching installed python packages found (nothing to do)."
fi

if [[ "$dry_run" == "1" ]]; then
  printf 'Packages to remove:\n'
  printf '%s\n' "$pkgs"
  printf '\nPlanned command:\n'
  if [[ "$noconfirm" == "1" ]]; then
    printf 'sudo pacman -Rns --noconfirm %s\n' \
      "$(printf '%s\n' "$pkgs" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g')"
  else
    printf 'sudo pacman -Rns %s\n' \
      "$(printf '%s\n' "$pkgs" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g')"
  fi
  exit 0
fi

_write_script "$output" "$noconfirm" "$include_python"
printf 'Wrote removal script: %s\n' "$output"

if [[ "$do_execute" == "1" ]]; then
  printf 'Executing: %s\n' "$output"
  bash "$output"
fi
