#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# hypr-low.sh
#
# Persistent Hyprland low-effects toggle (survives hyprctl reload).
#
# Commands:
#   hypr-low.sh on
#   hypr-low.sh off
#   hypr-low.sh clear
#   hypr-low.sh status
#   hypr-low.sh --help
#
# How it persists:
#   Writes an override config file in ~/.config/hypr/UserConfigs/ so that it is
#   sourced by your JaKooLit setup, then runs `hyprctl reload`.
#
# Files:
#   State (saved pre-low values):
#     $XDG_STATE_HOME/hypr-low/state.env
#     (fallback: ~/.local/state/hypr-low/state.env)
#
#   Override config (applied on reload):
#     ~/.config/hypr/UserConfigs/99-hypr-low-override.conf
# -----------------------------------------------------------------------------

function die() { printf 'Error: %s\n' "$*" >&2; exit 1; }

command -v hyprctl >/dev/null 2>&1 || die "hyprctl not found (Hyprland required)"
command -v awk     >/dev/null 2>&1 || die "awk not found"

STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_DIR="${STATE_HOME}/hypr-low"
STATE_FILE="${STATE_DIR}/state.env"

HYPR_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
OVERRIDE_FILE="${HYPR_DIR}/UserConfigs/99-hypr-low-override.conf"

function help() {
  cat <<EOF
hypr-low.sh

Usage:
  hypr-low.sh on
  hypr-low.sh off
  hypr-low.sh clear
  hypr-low.sh status
  hypr-low.sh --help

Meaning:
  on     Save current values, write LOW override file, hyprctl reload.
  off    Restore saved values by writing override file from state, reload.
  clear  Remove override + state file, reload (use your normal config).
  status Show current values and file paths.

Override file:
  ${OVERRIDE_FILE}

State file:
  ${STATE_FILE}
EOF
}

function getopt_val() {
  # Parse hyprctl getoption plain output. We accept:
  #   int:   <N>
  #   float: <N.N>
  #   set:   true|false  -> 1|0
  #   str:   <...>
  local key="$1"
  local out
  out="$(hyprctl getoption "$key" 2>/dev/null || true)"

  awk '
    match($0, /int:[[:space:]]*([0-9]+)/, m)     { print m[1]; exit }
    match($0, /float:[[:space:]]*([0-9.]+)/, m)  { print m[1]; exit }
    match($0, /set:[[:space:]]*(true|false)/, m) { print (m[1]=="true"?1:0); exit }
    match($0, /str:[[:space:]]*(.*)$/, m)        { print m[1]; exit }
  ' <<<"$out"
}

function must_get() {
  local key="$1" val
  val="$(getopt_val "$key")"
  if [[ -z "$val" ]]; then
    printf 'Error: Could not read option "%s". Raw output:\n' "$key" >&2
    hyprctl getoption "$key" >&2 || true
    exit 1
  fi
  printf '%s' "$val"
}

function write_override() {
  # Args: anim blur shad vfr (0/1)
  local anim="$1" blur="$2" shad="$3" vfr="$4"

  mkdir -p -- "$(dirname "$OVERRIDE_FILE")"

  cat >"$OVERRIDE_FILE" <<EOF_CFG
# ---------------------------------------------------------------------------
# Auto-generated by hypr-low.sh
# Timestamp: $(date -Is)
# ---------------------------------------------------------------------------

animations {
  enabled = ${anim}
}

decoration {
  shadow {
    enabled = ${shad}
  }
  blur {
    enabled = ${blur}
  }
}

misc {
  vfr = ${vfr}
}
EOF_CFG
}

function save_state() {
  mkdir -p "$STATE_DIR"
  local anim blur shad vfr
  anim="$(must_get "animations:enabled")"
  blur="$(must_get "decoration:blur:enabled")"
  shad="$(must_get "decoration:shadow:enabled")"
  vfr="$(must_get "misc:vfr")"

  cat >"$STATE_FILE" <<EOF_STATE
ANIM="$anim"
BLUR="$blur"
SHAD="$shad"
VFR="$vfr"
EOF_STATE
}

function reload_hypr() {
  hyprctl reload >/dev/null 2>&1 || true
}

function cmd_on() {
  save_state
  write_override 0 0 0 1
  reload_hypr
}

function cmd_off() {
  [[ -f "$STATE_FILE" ]] || die "No saved state at $STATE_FILE (run: on)"
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  write_override "${ANIM:-1}" "${BLUR:-1}" "${SHAD:-1}" "${VFR:-1}"
  reload_hypr
}

function cmd_clear() {
  rm -f -- "$OVERRIDE_FILE" "$STATE_FILE"
  reload_hypr
}

function cmd_status() {
  printf 'animations:enabled=%s\n'        "$(getopt_val "animations:enabled")"
  printf 'decoration:blur:enabled=%s\n'   "$(getopt_val "decoration:blur:enabled")"
  printf 'decoration:shadow:enabled=%s\n' "$(getopt_val "decoration:shadow:enabled")"
  printf 'misc:vfr=%s\n'                  "$(getopt_val "misc:vfr")"
  printf 'override_exists=%s\n'           "$([[ -f "$OVERRIDE_FILE" ]] && echo yes || echo no)"
  printf 'saved_state=%s\n'               "$([[ -f "$STATE_FILE" ]] && echo yes || echo no)"
  printf 'override_file=%s\n'             "$OVERRIDE_FILE"
  printf 'state_file=%s\n'                "$STATE_FILE"
}

case "${1:-}" in
  -h|--help|"")
    help
    ;;
  on)
    cmd_on
    ;;
  off)
    cmd_off
    ;;
  clear)
    cmd_clear
    ;;
  status)
    cmd_status
    ;;
  *)
    die "Usage: hypr-low.sh on|off|clear|status|--help"
    ;;
esac
