#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# hypr-effects
#
# Toggle Hyprland visual effects using JaKooLit Hyprland-Dots layout, with
# persistent overrides (survive `hyprctl reload` and restart).
#
# Presets:
#   high     Animations + blur + shadows (incl. popups/special blur)
#   medium   Animations + light blur + lighter shadows (no popups/special blur)
#   low      Minimal effects (no blur/shadows; animations off; borderangle off)
#   default  Revert to dotfiles defaults (disable overrides)
#
# How persistence works (JaKooLit Hyprland-Dots):
#   ~/.config/hypr/hyprland.conf sources:
#     ~/.config/hypr/UserConfigs/UserSettings.conf
#   This script ensures UserSettings.conf sources an override file:
#     ~/.config/hypr/UserConfigs/99-hypr-effects-override.conf
# -----------------------------------------------------------------------------

# ------------------------------- constants -----------------------------------

MARK_BEGIN="# --- hypr-effects managed begin ---"
MARK_END="# --- hypr-effects managed end ---"

# -------------------------------- utilities ----------------------------------

function die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

function have() { command -v "$1" >/dev/null 2>&1; }

function now_iso() {
  date -Is 2>/dev/null || date
}

function help_pager_cmd() {
  if [[ -n "${HELP_PAGER:-}" ]]; then
    printf '%s' "$HELP_PAGER"
    return 0
  fi
  if have less; then
    printf '%s' "less -R"
    return 0
  fi
  printf '%s' "cat"
}

function show_help() {
  local pager
  pager="$(help_pager_cmd)"

  cat <<'EOF' | eval "$pager"
hypr-effects

Usage:
  hypr-effects high|medium|low|default
  hypr-effects status
  hypr-effects install
  hypr-effects uninstall
  hypr-effects --help

Options:
  --no-reload   Write/adjust files but do not run `hyprctl reload`.
  --reload      Force reload (default for preset changes).

Notes:
  - This is designed for JaKooLit Hyprland-Dots where hyprland.conf sources
    ~/.config/hypr/UserConfigs/UserSettings.conf.
  - The override file is sourced *late* (via UserSettings.conf), so it wins over
    UserDecorations.conf and UserAnimations.conf.
  - borderangle loop can force continuous rendering; medium/low disable it.

Files:
  Override:
    ~/.config/hypr/UserConfigs/99-hypr-effects-override.conf
  Hook target:
    ~/.config/hypr/UserConfigs/UserSettings.conf

Examples (5+):
  hypr-effects status
  hypr-effects low
  hypr-effects medium
  hypr-effects high
  hypr-effects default
  hypr-effects install
  HELP_PAGER="cat" hypr-effects --help

Compatibility wrappers (optional):
  To keep your old commands, symlink:
    ln -sf /usr/local/bin/hypr-effects /usr/local/bin/hypr-high
    ln -sf /usr/local/bin/hypr-effects /usr/local/bin/hypr-medium
    ln -sf /usr/local/bin/hypr-effects /usr/local/bin/hypr-low
    ln -sf /usr/local/bin/hypr-effects /usr/local/bin/hypr-default
    ln -sf /usr/local/bin/hypr-effects /usr/local/bin/hypr-mode

  Then:
    hypr-high      => preset high
    hypr-medium    => preset medium
    hypr-low       => preset low
    hypr-default   => preset default
    hypr-mode      => status
EOF
}

function lower() {
  tr '[:upper:]' '[:lower:]' <<<"${1:-}"
}

function require_hyprctl() {
  have hyprctl || die "hyprctl not found (Hyprland required)"
}

# Parse `hyprctl getoption <key>` output into a single value.
function getopt_val() {
  local key="$1" out
  out="$(hyprctl getoption "$key" 2>/dev/null || true)"

  awk '
    match($0, /int:[[:space:]]*([0-9]+)/, m)     { print m[1]; exit }
    match($0, /float:[[:space:]]*([0-9.]+)/, m)  { print m[1]; exit }
    match($0, /set:[[:space:]]*(true|false)/, m) { print (m[1]=="true"?1:0); exit }
    match($0, /str:[[:space:]]*(.*)$/, m)        { print m[1]; exit }
  ' <<<"$out"
}

function ensure_dirs() {
  mkdir -p -- "$USERCFG_DIR"
  mkdir -p -- "$STATE_DIR"
}

function backup_file_if_exists() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  cp -a -- "$f" "${f}.bak.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true
}

function ensure_override_file_exists() {
  ensure_dirs
  if [[ ! -f "$OVERRIDE_FILE" ]]; then
    cat >"$OVERRIDE_FILE" <<EOF_CFG
# ---------------------------------------------------------------------------
# Auto-generated by hypr-effects
# Created: $(now_iso)
# Preset: default
# ---------------------------------------------------------------------------
EOF_CFG
  fi
}

function ensure_user_settings_hook() {
  ensure_dirs
  [[ -f "$USER_SETTINGS" ]] || {
    cat >"$USER_SETTINGS" <<EOF_CFG
# ---------------------------------------------------------------------------
# UserSettings.conf (JaKooLit Hyprland-Dots)
# This file is intended for your own settings and is sourced by hyprland.conf.
# ---------------------------------------------------------------------------
EOF_CFG
  }

  if grep -Fq "$MARK_BEGIN" "$USER_SETTINGS"; then
    return 0
  fi

  backup_file_if_exists "$USER_SETTINGS"
  {
    printf '\n%s\n' "$MARK_BEGIN"
    printf '# Sourcing hypr-effects overrides (managed by hypr-effects)\n'
    printf 'source = %s\n' "$OVERRIDE_FILE"
    printf '%s\n' "$MARK_END"
  } >>"$USER_SETTINGS"
}

function uninstall_user_settings_hook() {
  [[ -f "$USER_SETTINGS" ]] || return 0

  if ! grep -Fq "$MARK_BEGIN" "$USER_SETTINGS"; then
    return 0
  fi

  backup_file_if_exists "$USER_SETTINGS"

  local tmp
  tmp="$(mktemp)"
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
    $0 == b { skip=1; next }
    skip && $0 == e { skip=0; next }
    !skip { print }
  ' "$USER_SETTINGS" >"$tmp"

  mv -- "$tmp" "$USER_SETTINGS"
}

function write_override_default() {
  ensure_override_file_exists
  cat >"$OVERRIDE_FILE" <<EOF_CFG
# ---------------------------------------------------------------------------
# Auto-generated by hypr-effects
# Updated: $(now_iso)
# Preset: default
#
# This is intentionally a no-op file. With the hook present, Hyprland will
# source this file, but it will not override anything. Your dotfiles defaults
# remain in effect.
# ---------------------------------------------------------------------------
EOF_CFG
}

function write_override_low() {
  ensure_override_file_exists
  cat >"$OVERRIDE_FILE" <<EOF_CFG
# ---------------------------------------------------------------------------
# Auto-generated by hypr-effects
# Updated: $(now_iso)
# Preset: low
# ---------------------------------------------------------------------------

animations {
  enabled = false
  # Disable borderangle loop explicitly (can force continuous rendering).
  animation = borderangle, 0
}

decoration {
  shadow {
    enabled = false
  }
  blur {
    enabled = false
  }
}

misc {
  vfr = true
  animate_manual_resizes = false
  animate_mouse_windowdragging = false
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
EOF_CFG
}

function write_override_medium() {
  ensure_override_file_exists
  cat >"$OVERRIDE_FILE" <<EOF_CFG
# ---------------------------------------------------------------------------
# Auto-generated by hypr-effects
# Updated: $(now_iso)
# Preset: medium
# ---------------------------------------------------------------------------

animations {
  enabled = true
  # Keep animations, but disable borderangle loop to avoid constant rendering.
  animation = borderangle, 0
}

decoration {
  shadow {
    enabled = true
    range = 2
    render_power = 2
  }
  blur {
    enabled = true
    size = 3
    passes = 2
    new_optimizations = true
    xray = true
    ignore_opacity = true

    # These can be expensive; keep them off in medium.
    special = false
    popups = false
  }
}

misc {
  vfr = true
  animate_manual_resizes = false
  animate_mouse_windowdragging = false
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
EOF_CFG
}

function write_override_high() {
  ensure_override_file_exists
  cat >"$OVERRIDE_FILE" <<EOF_CFG
# ---------------------------------------------------------------------------
# Auto-generated by hypr-effects
# Updated: $(now_iso)
# Preset: high
# ---------------------------------------------------------------------------

animations {
  enabled = true

  # Ensure the curve exists, then re-enable borderangle loop.
  bezier = liner, 1, 1, 1, 1
  animation = borderangle, 1, 180, liner, loop
}

decoration {
  shadow {
    enabled = true
    range = 3
    render_power = 1
  }
  blur {
    enabled = true
    size = 6
    passes = 3
    new_optimizations = true
    xray = true
    ignore_opacity = true
    special = true
    popups = true
  }
}

misc {
  vfr = true
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
EOF_CFG
}

function save_state_preset() {
  ensure_dirs
  local preset="$1"
  cat >"$STATE_FILE" <<EOF_STATE
PRESET="$preset"
UPDATED="$(now_iso)"
OVERRIDE_FILE="$OVERRIDE_FILE"
USER_SETTINGS="$USER_SETTINGS"
EOF_STATE
}

function current_preset_from_override() {
  [[ -f "$OVERRIDE_FILE" ]] || { printf '%s' "missing"; return 0; }
  awk '
    match($0, /^# Preset:[[:space:]]*([a-zA-Z0-9_-]+)/, m) { print m[1]; exit }
  ' "$OVERRIDE_FILE" 2>/dev/null || true
}

function cmd_status() {
  require_hyprctl
  ensure_override_file_exists

  printf 'preset=%s\n' "$(current_preset_from_override)"
  printf 'override_exists=%s\n' "$([[ -f "$OVERRIDE_FILE" ]] && echo yes || echo no)"
  printf 'hook_present=%s\n' "$([[ -f "$USER_SETTINGS" ]] && \
    grep -Fq "$MARK_BEGIN" "$USER_SETTINGS" && echo yes || echo no)"
  printf 'override_file=%s\n' "$OVERRIDE_FILE"
  printf 'user_settings=%s\n' "$USER_SETTINGS"
  printf '\n'

  printf 'animations:enabled=%s\n' \
    "$(getopt_val "animations:enabled")"
  printf 'decoration:blur:enabled=%s\n' \
    "$(getopt_val "decoration:blur:enabled")"
  printf 'decoration:blur:size=%s\n' \
    "$(getopt_val "decoration:blur:size")"
  printf 'decoration:blur:passes=%s\n' \
    "$(getopt_val "decoration:blur:passes")"
  printf 'decoration:blur:special=%s\n' \
    "$(getopt_val "decoration:blur:special")"
  printf 'decoration:blur:popups=%s\n' \
    "$(getopt_val "decoration:blur:popups")"
  printf 'decoration:shadow:enabled=%s\n' \
    "$(getopt_val "decoration:shadow:enabled")"
  printf 'decoration:shadow:range=%s\n' \
    "$(getopt_val "decoration:shadow:range")"
  printf 'misc:vfr=%s\n' \
    "$(getopt_val "misc:vfr")"
  printf 'misc:disable_hyprland_logo=%s\n' \
    "$(getopt_val "misc:disable_hyprland_logo")"
  printf 'misc:disable_splash_rendering=%s\n' \
    "$(getopt_val "misc:disable_splash_rendering")"
}

function reload_hypr() {
  require_hyprctl
  hyprctl reload >/dev/null 2>&1 || die "hyprctl reload failed"
}

# --------------------------------- main --------------------------------------

HYPR_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
USERCFG_DIR="${HYPR_DIR}/UserConfigs"
USER_SETTINGS="${USERCFG_DIR}/UserSettings.conf"
OVERRIDE_FILE="${USERCFG_DIR}/99-hypr-effects-override.conf"

STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_DIR="${STATE_HOME}/hypr-effects"
STATE_FILE="${STATE_DIR}/state.env"

RELOAD=1

# Allow calling via symlinked names.
INFERRED=""
case "$(basename "$0")" in
  hypr-high)    INFERRED="high" ;;
  hypr-medium)  INFERRED="medium" ;;
  hypr-low)     INFERRED="low" ;;
  hypr-default) INFERRED="default" ;;
  hypr-mode)    INFERRED="status" ;;
esac

if [[ -n "$INFERRED" && $# -eq 0 ]]; then
  set -- "$INFERRED"
fi

# Flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-reload) RELOAD=0; shift ;;
    --reload)    RELOAD=1; shift ;;
    -h|--help)   show_help; exit 0 ;;
    *) break ;;
  esac
done

CMD="$(lower "${1:-}")"

case "$CMD" in
  ""|help)
    show_help
    exit 0
    ;;
  install)
    ensure_override_file_exists
    ensure_user_settings_hook
    printf 'Installed hook in: %s\n' "$USER_SETTINGS"
    printf 'Override file:      %s\n' "$OVERRIDE_FILE"
    exit 0
    ;;
  uninstall)
    uninstall_user_settings_hook
    rm -f -- "$OVERRIDE_FILE" "$STATE_FILE" 2>/dev/null || true
    printf 'Removed hook from:  %s\n' "$USER_SETTINGS"
    printf 'Removed override:   %s\n' "$OVERRIDE_FILE"
    exit 0
    ;;
  status)
    cmd_status
    exit 0
    ;;
  high|medium|low|default)
    require_hyprctl
    ensure_user_settings_hook

    case "$CMD" in
      high)    write_override_high ;;
      medium)  write_override_medium ;;
      low)     write_override_low ;;
      default) write_override_default ;;
    esac

    save_state_preset "$CMD"

    if [[ "$RELOAD" -eq 1 ]]; then
      reload_hypr
    fi

    cmd_status
    exit 0
    ;;
  *)
    die "Usage: hypr-effects high|medium|low|default|status|install|uninstall|--help"
    ;;
esac
